### ISSUE TITLE
Join Universal Healthcare Action Blitz as a Major Partner

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#195] opened 2017-05-14 11:47 UTC
#### Description

Universal Healthcare Action Blitz is a one-day event in New York where several progressive professional networks will come together to create tech, media, and content assets and build resource capacity for the fight for Universal Health Care.

To create technological and creative assets for the organizations fighting for Universal Healthcare. ProgCode has gone through a series of interviews with health care organizations, and have pinpointed ways we can be of  support for the fight for Universal Health Care. For this Health Care Blitz, we aim to build a healthcare calculator of the public at large and for small businesses, a peer-to-peer petitioning system, and a speaker calendar/needs pipeline. 

The Universal Health Care bill in the state senate right now only needs two YES, and a push for the Health Committee chair to push for it to be put in the agenda. That's why this blitz is necessary.

#### Problem

There are a lot of professional progressive networks in New York which encompasses Progressive coders, data analysts, designers, advertisers, videographers, documentarians, editors, etc. This action blitz aims to gather these talents and have a day of action focused on boosting the tech and creative assets of these organizations.

#### Benefit

This could be a start of other action blitzes where we aim to reachout to stake holders, build relationships, and boost their tech and creative assets. Great way to solidify partnerships as well.

The Universal Health Care bill in the state senate right now only needs two YES, and a push for the Health Committee chair to push for it to be put in the agenda. That's why this blitz is necessary.

IF we can help get NY to set the stage for Universal Health Care, we can set the stage for a single-payer healthcare nationally.

Sets the stage of a highly issue-focused, issue-driven action to be done by emergent networks.

#### Plan

- [ ] Consent
- [ ] Have our logo in the website

#### Decision Making

By Consent

## Optional Information

* [Proposal](https://docs.google.com/document/d/164DoWmmXOLHatEj8TNvd3cYHSbdVct2xaoLRBNJnjZQ/edit#)
* [Strategy](https://docs.google.com/document/d/1e2D-smffMRPCeUKG7gKYAO3VWBrbjdta7tyl7LIJuR4/edit)

#### Reference link(s)

...

**Comment by jpb5013** [comment] 2017-05-14 12:31
If it's a ProgCode action I'd want to ensure that these efforts are building for scalable execution, not just for New York. It seems to be written that way but wanted to explicitly call it out. 

Prog Hack Night and whatever else seem like good avenues. Only concern is the March for Truth aspect, which seems to be about Russia. I'm not seeing the connection to Healthcare and would be uneasy with ProgCode being affiliated with the event. The Russia thing has been a Democrat talking point for quite a while, so this aspect feels rather partisan to me and out of scope for ProgCode. 

https://www.marchfortruth.info/

**Comment by rcscastillo** [comment] 2017-05-14 13:08
The March for Truth aspect of it is just to take folks from the march and have them interviewed by OnStack. There's no co-partnership with March for Truth at all, and the thinking is "since the march is happening, and there are a lot of people going there, why not interview some of those who are there for their stories on Healthcare?" there are other actions happening that day (I think one in Long Island calling for the support of the bill to Assemblyman Hannon).

It is indeed just in New York, we're looking if we can do this locally and pull it off, it can expand nationally.

**Comment by rcscastillo** [comment] 2017-05-14 13:20
On the partisan definition, again, I feel that that definition is contentious. What may be partisan to you may not be partisan to anyone. For me at least, your definition of partisanship here is problematic. Unless we define "partisanship" as strictly, "working towards an election of a candidate adhering to a candidate." or if we have a definite definition of what is or what is not partisan, we can only adhere to a dictionary/wikipedia definition of it which is

> In politics, a partisan is a committed member of a political party. In multi-party systems, the term is used for politicians who strongly support their party's policies and are reluctant to compromise with their political opponents.

I will be opening an issue for this

**Comment by rcscastillo** [comment] 2017-05-14 14:16
Also applied edits for clarity, @jpb5013 ! ^_^

**Comment by rcscastillo** [comment] 2017-05-17 13:51
Here's the request from ActionBlitz


=====  EMAIL STARTS HERE =====

Hi ProgCode team, 

I am reaching out and would love to ask for the participation of ProgCode at the Universal Health Care Action Blitz, happening on June 3 at Civic Hall, from 9am-6pm.

 A number of progressive professional networks are working together and coordinating with organizations pushing for universal healthcare. This event coincides with the week of action being organized for Universal Healthcare.

The Action Blitz is designed to boost the tech and creative assets of healthcare organizations. From the tech sector, we are going to build Health Care calculators, peer-to-peer petitioning, and Speaker calendars, and help make campaign websites.

On the  creatives side, we aim to create hundreds of graphics in support for the cause, produce in depth health care stories , man on the ground videos for folks on the ground, and more.

Your organization's participation is highly valued for the success of this day of action. [We only have less than 50 days to bring universal health care in New York!](http://www.passnyhealth.com/)

This is our Call to Action!
Become a signal booster for our social media / marketing push
Ask your members to RSVP for the event here
If you have relationships with media partners, pls kindly offer the event for them to cover (template will be sent next week)
We are actively seeking project managers for each of our project areas. If you are interested (or know someone interested) in becoming a project mgr for one of the applications/creative projects, pls let us know
We are also looking for coders, designers, videographers, branding experts, graphic designers and social media experts who could come in on the day to participate in the event/leading up to it.
If you are interested in being part of the steering committee, please let us know! 

I would love to go on a call with you to discuss more about this. Pls let me know when would be a great time to do so. More information at the proposal attached.

In solidarity,

Ananda, Ellen, David, Kathryn, Ling, Rapi
UH ActionBlitz Steering Committee

=====  EMAIL ENDS HERE =====

**Comment by rcscastillo** [comment] 2017-05-22 04:17
Backing this off, as with HackTheBan, ProgCode as a network cannot participate as an official partner but rather as a force of support.

**Closed by rcscastillo** 2017-05-22 04:17 UTC
Labels: by-consent, strategic-partnerships
